packages:
    - 'packages/*'
    - 'playgrounds/*'

catalog:
    'typescript': ^5.7.3

catalogs:
    tw3:
        'tailwindcss': ^3

    tw4:
        'tailwindcss': ^4
        '@tailwindcss/vite': ^4
